name: uts
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_rating_bar: ^4.0.0
  get: ^4.6.1
  google_fonts: ^4.0.4
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.1.5
  lottie: ^3.0.0
  url_launcher: ^6.0.9
  http: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.1.2
  url_launcher: ^6.2.3
  lottie: ^3.0.0

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/images/
    - asset/screenshot/
    - asset/gambar/
    - asset/dokter/
    - asset/jason/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages